apiVersion: apps/v1 
kind: Deployment
metadata:
  name: predict-imdb 
  namespace: ai-project
  labels:
    app: imdb-server
spec:
  revisionHistoryLimit: 3
  replicas: 1 
  selector:
    matchLabels:
      app: imdb-server
  template:
    metadata:
      labels:
        app: imdb-server
    spec:
      containers:
      - name: app
        image: image-registry.openshift-image-registry.svc:5000/openshift/app:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
         - echo "start";
           git clone https://github.com/amirgholipour/imdb_deploy;
           cd imdb_deploy;
           pip install -r requirements.txt;
           python server.py;
        ports:
        - containerPort: 8080
          protocol: TCP
