apiVersion: apps/v1 
kind: Deployment
metadata:
  name: predict-imdb-{{  experiment_id }}
  namespace: default
  labels:
    app: imdb-server
spec:
  annotations:
    project_name: {{  model_name }}
    deployment_version: "{{  experiment_id }}"
  name: {{  model_name }}-spec  
  revisionHistoryLimit: 3
  replicas: 2 
  selector:
    matchLabels:
      app: imdb-server
  template:
    metadata:
      labels:
        app: imdb-server
    spec:
      containers:
      - name: app
        image: "image-registry.openshift-image-registry.svc:5000/{{project}}/{{image_name}}"
        imagePullPolicy: Always
        name: {{  model_name }}predictor
        command: ["/bin/sh", "-c"]
        args:
         - echo "start";
           git clone https://github.com/amirgholipour/imdb_keras;
           cd imdb_keras;
           pip install -r requirements.txt;
           python server.py;
        ports:
        - containerPort: 8080
          protocol: TCP
