apiVersion: v1
kind: Service
metadata:
  name: predict-imdb-service
  labels:
    app: imdb-server
    
spec:
  annotations:
    project_name: {{  model_name }}
    deployment_version: "{{  experiment_id }}"
  name: {{  model_name }}-spec
  predictors:
    - componentSpecs:
        - hpaSpec:
            maxReplicas: 5
            metrics:
              - resource:
                  name: cpu
                  targetAverageUtilization: 80
                type: Resource
            minReplicas: 1
          spec:
            containers:

              - image: "image-registry.openshift-image-registry.svc:5000/{{project}}/{{image_name}}"
                imagePullPolicy: Always
                name: {{  model_name }}predictor
                env:
                  - name: MODEL_NAME
                    value: "Predictor"
                  - name: SERVICE_TYPE
                    value: MODEL
                  - name: GRPC_PORT
                    value: "5007"
                  - name: METRICS_PORT
                    value: "6007"
                  - name: HTTP_PORT
                    value: "9001"
        graph:
          name: {{  model_name }}predictor

          endpoint:
            type: MODEL
            service_host: localhost
            service_port: 9000
          type: predictor
        annotations:
          predictor_version: "{{  experiment_id }}"
          team: aiteam
          
        labels:
          team: aiteam
          version: predictor

      replicas: 1


  ports:
    - port: 8080
  selector:
    app: imdb-server
  type: NodePort
